"""empty message

Revision ID: 14410cc7ebd6
Revises: b3d86c2f7a56
Create Date: 2024-07-07 14:13:09.598853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14410cc7ebd6'
down_revision = 'b3d86c2f7a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles_Id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Vehicles', ['vehicles_Id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicles_Id')

    # ### end Alembic commands ###
